name: dbldart
description: Discord Bot List API for Dart
version: 0.2.0
homepage: https://github.com/voximity/dbldart
authors:
  - vox <0zanfran@gmail.com>
  - l7ssha <szymon.uglis@tuta.io>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  http: